#pragma once
#include "uiDialog.h"
// #include "cMap.h"
#include "cObject.h"
// #include "cScript.h"
#include "uiChannel.h"
// #include "uiGrids.h"

#include "uiHeader.h"
// #include "uiItem.h"
// #include "uiJob.h"
#include "uiManager.h"
#include "uiMap.h"
#include "uiMenu.h"
#include "uiPad.h"
//#include "uiPet.h"
// #include "uiRank.h"
#include "uiRole.h"
// #include "uiSee.h"
// #include "uiShichen.h"
// #include "uiShop.h"
// #include "uiSmap.h"